name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '30 3 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          nix flake update --commit-lock-file --commit-lockfile-summary "flake.lock: Update"
      - name: Update plugins.json
        run: |
          nix run .#update
          git add plugins.json && git commit -m 'update plugins.json' || true
      - name: Build flake
        run: |
          nix build --show-trace
      - name: Push to main
        run: |
          git push
